# Generated by Django 4.2.9 on 2026-10-02 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_no', models.CharField(max_length=64, unique=True, verbose_name='操作单号')),
                ('type', models.CharField(choices=[('seal', '封装'), ('split', '拆分'), ('merge', '合并'), ('repack', '重新封装'), ('issue', '领用'), ('freeze', '冻结'), ('unfreeze', '解冻')], max_length=20, verbose_name='操作类型')),
                ('receiver', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='操作总量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '封签操作',
                'verbose_name_plural': '封签操作',
                'db_table': 'wh_seal_operation',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_no', models.CharField(max_length=64, unique=True, verbose_name='封签号')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='封装数量')),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('frozen', '冻结'), ('issued', '已领用'), ('terminated', '已终结')], default='in_stock', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='封装时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seals', to='warehouse.goods', verbose_name='货物')),
            ],
            options={
                'verbose_name': '封签',
                'verbose_name_plural': '封签',
                'db_table': 'wh_seal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('input', '投入'), ('output', '产出'), ('freezing', '冻结对象')], max_length=20, verbose_name='节点角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='warehouse.sealoperation', verbose_name='所属操作')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_nodes', to='warehouse.seal', verbose_name='封签')),
            ],
            options={
                'verbose_name': '操作节点关联',
                'verbose_name_plural': '操作节点关联',
                'db_table': 'wh_operation_node',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edges', to='warehouse.sealoperation', verbose_name='所属操作')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_edges', to='warehouse.seal', verbose_name='源封签')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_edges', to='warehouse.seal', verbose_name='目标封签')),
            ],
            options={
                'verbose_name': '谱系边',
                'verbose_name_plural': '谱系边',
                'db_table': 'wh_lineage_edge',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lineageedge',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_id', models.F('target_id')), _negated=True), ('source_id__isnull', True), ('target_id__isnull', True), _connector='OR'), name='lineage_edge_no_self_loop'),
        ),
    ]
