# Generated by Django 4.2.9 on 2026-10-02 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_no', models.CharField(max_length=40, unique=True, verbose_name='封签编号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='当前数量')),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='封装数量')),
                ('status', models.CharField(choices=[('active', '在库'), ('frozen', '已冻结'), ('issued', '已领用'), ('consumed', '已转化')], default='active', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seals', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seals', to='warehouse.goods', verbose_name='货物')),
            ],
            options={
                'verbose_name': '封签',
                'verbose_name_plural': '封签',
                'db_table': 'cu_seal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_no', models.CharField(max_length=40, unique=True, verbose_name='操作单号')),
                ('operation_type', models.CharField(choices=[('register', '初始登记'), ('split', '拆分'), ('merge', '合并'), ('repack', '重新封装'), ('issue', '领用'), ('freeze', '冻结'), ('unfreeze', '解冻')], max_length=20, verbose_name='操作类型')),
                ('receiver', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('receiver_dept', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('input_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='投入数量')),
                ('output_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='产出数量')),
                ('conserved', models.BooleanField(blank=True, default=None, help_text='仅拆分/合并/重新封装需要校验；为空表示该操作类型不适用', null=True, verbose_name='数量守恒校验通过')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seal_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '谱系操作',
                'verbose_name_plural': '谱系操作',
                'db_table': 'cu_seal_operation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SealOperationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', '投入'), ('out', '产出')], max_length=4, verbose_name='方向')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='涉及数量')),
                ('status_before', models.CharField(blank=True, max_length=20, verbose_name='操作前状态')),
                ('status_after', models.CharField(max_length=20, verbose_name='操作后状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='custody.sealoperation', verbose_name='谱系操作')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_nodes', to='custody.seal', verbose_name='封签')),
            ],
            options={
                'verbose_name': '谱系边',
                'verbose_name_plural': '谱系边',
                'db_table': 'cu_seal_operation_node',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['seal', 'direction'], name='cu_seal_ope_seal_id_da24d3_idx'), models.Index(fields=['operation', 'direction'], name='cu_seal_ope_operati_fdaf9c_idx')],
                'unique_together': {('operation', 'seal', 'direction')},
            },
        ),
    ]
